services:
  - type: web
    name: calorie-mama-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: CALORIE_MAMA_API_KEY
        value: 13eea10ec9c3d3c7703dfa0e2c6da653